### ISSUE TITLE
Error received, please advise

### ISSUE THREAD

**Issue by stevenljr** [shopgoodwill-sniper/shopgoodwill-auction-sniper#44]
Hello,

I am receiving this error, can you please advise what I should do? 

![Screenshot (901)](https://github.com/user-attachments/assets/9a5d724d-f9d4-411e-9a57-d451ae97fabe)
Thank you

**Comment by shopgoodwill-sniper** [comment]
Hi stevenljr,

The error you are receiving only occurs on some systems with super strict security restrictions, so in order to resolve it you simply need to right-click on the Powershell terminal app instead of left-click and click on the "Run As Administrator" context menu item to launch the Powershell app as administrator and then you can proceed with copy and pasting the Bid Sniper install/update command from our homepage at Snipeable.com and that will resolve the error you are experiencing. 

Please let us know if we can be of further assistance.

Best regards,
Technical Support
Snipeable.com

**Comment by stevenljr** [comment]
It worked thank you!

**Comment by shopgoodwill-sniper** [comment]
That's great news! We will build in elevation of permissions into the installer so you don't have to do that manually next time.
