### ISSUE TITLE
app says sniped but snipe was never entered

### ISSUE THREAD

**Issue by superrama** [shopgoodwill-sniper/shopgoodwill-auction-sniper#47]
Set an overnight snipe. Woke up to app saying it sniped it but the bid was never entered according to the history and it should have been high enough to register
![Screenshot 2024-09-29 122103](https://github.com/user-attachments/assets/748e7aaf-7c83-4420-8971-b18265a62d3e)
![Screenshot 2024-09-29 122050](https://github.com/user-attachments/assets/edb55455-d646-4b63-90bc-f24c86685f83)

**Comment by shopgoodwill-sniper** [comment]
Dear superrama,

It looks like the issue you're experiencing has already been resolved in the latest version of Bid Sniper. The new version no longer displays "Sniped!" but clearly indicates whether you won or lost the auction. It seems you're currently using an older version.

To update to the latest version, simply run the install/update command from our homepage: http://Snipeable.com

If you need any further assistance, feel free to reach out.

Best regards,
Customer Service
Snipeable.com

**Comment by superrama** [comment]
but why would have lost the auction? it was higher than the current bid?

**Comment by shopgoodwill-sniper** [comment]
The old version had issues with the sniping logic that we refactored in the newest version, please update to the latest version to resolve your issue.

Best regards,
Customer Service
Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
FYI, We just released a new version of the ShopGoodwill Auction Sniper where we have completely rewritten the sniping engine inside it and the database in it as well to be more efficient and 100% accurate because the old version had some users complaining that sometimes it would miss auctions for them and our goal here is to make the sniping software 100% solid as possible so that it never fails and that is exactly what we have done here in this new version, we have made the sniping accuracy in it 100% accurate and never misses now, so please feel free to update to the latest version simply by running the install/update command from our homepage at Snipeable.com again, the new version numbers are as follows if you want to confirm you are indeed using the latest version once updated:

ShopGoodWill Auction Sniper Windows version is 25.03.23.1514
ShopGoodWill Auction Sniper Mac version is 25.03.23.1645
