### ISSUE TITLE
FAILS TO WORK!!!!!! HELP!

### ISSUE THREAD

**Issue by govcontracting** [shopgoodwill-sniper/shopgoodwill-auction-sniper#48]
I tried to snipe about 25 auctions from SHOPGOODWILL and every single one of them ended with FAILED after the auction passed.  I was the highest bidder on about 90% of the auctions.  What is going on!?!?!??!?!  I want a refund if this isn't going to work!

**Comment by shopgoodwill-sniper** [comment]
Hello govcontracting,

Please update to the latest version by running the install/update command again from our homepage at Snipeable.com

Best regards,
Technical Support
Snipeable.com

**Comment by govcontracting** [comment]
I did this and it seems to have won one of the auctions, but how come it says I lost when my bid was way higher than the winning bid ?Sent from my iPhoneOn Oct 6, 2024, at 1:53 AM, ShopGoodwill Sniper ***@***.***> wrote:﻿
Hello govcontracting,
Please update to the latest version by running the install/update command again from our homepage at Snipeable.com
Best regards,
Technical Support
Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
If you want it to win an auction 100% guaranteed then please use the auto-maximum bid feature which basically means leave the maximum bid field empty when adding a snipe, but for a better explanation of why you lost a particular auction, simply hover your mouse over the lost status text within the my snipes section and a little status text will show you the exact reason why it lost that particular auction, just move your mouse over the status text and hold it there for about 2 seconds and the status text will appear with a reason.

Best regards,
Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
FYI, We just released a new version of the ShopGoodwill Auction Sniper where we have completely rewritten the sniping engine inside it and the database in it as well to be more efficient and 100% accurate because the old version had some users complaining that sometimes it would miss auctions for them and our goal here is to make the sniping software 100% solid as possible so that it never fails and that is exactly what we have done here in this new version, we have made the sniping accuracy in it 100% accurate and never misses now, so please feel free to update to the latest version simply by running the install/update command from our homepage at Snipeable.com again, the new version numbers are as follows if you want to confirm you are indeed using the latest version once updated:

ShopGoodWill Auction Sniper Windows version is 25.03.23.1514
ShopGoodWill Auction Sniper Mac version is 25.03.23.1645
