### ISSUE TITLE
LOST even with my bid $60 higher than the winner

### ISSUE THREAD

**Issue by Bidnabber** [shopgoodwill-sniper/shopgoodwill-auction-sniper#56]
Tried to snipe an auction.  LOST even with my bid $60 higher than the winner.  I heard it make the lost noise.  Is there issues.  I have won 4 so far by sniping.  

I should not of lost that one !?  When I lose does it still cost the snipe I paid for?

**Comment by shopgoodwill-sniper** [comment]
Hi, if it won 4 already but lost 1 even when your bid was $60 higher than the winner, that usually means that you didn't pay for your won auctions on Shopgoodwill website on time, they require for you to pay for your already won items before you can win more basically, so when you win an auction make sure you pay for it on the Shopgoodwill website right away so that it doesn't prevent you from winning more!

Regarding your other question, yes, you still pay for the snipe whether you win or lose.

Best regards,
Technical Support
Snipeable.com

**Comment by Bidnabber** [comment]
The 4 I have won have been spaced out time wise and I am totally paid up.
I generally pay within hours of a win.  Had no open orders.

So I guess I just got screwed without a true clue to what happened.

**Comment by shopgoodwill-sniper** [comment]
Also move your mouse over the status text of that auction under the "My Snipes" section inside the app and it will show you the exact reason why you lost that one.

**Comment by shopgoodwill-sniper** [comment]
Also ensure you are using the latest version of the software we just released a new version yesterday so update by running the install/update command again from our homepage at Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
It shows you the exact reason you lost if you hover your mouse over the status text in the app and hold it there on the status text for a few seconds!

**Comment by Bidnabber** [comment]
Ok thanks It says the auction closed at blah blah.  So it looks like it
didnt get the bid in on time.  Also if it doesn't automatically update I am
probably running an older version.

**Comment by shopgoodwill-sniper** [comment]
Yea, it sounds like you are using the old version which explains why it missed the auction, the new version is about 4x faster!

**Comment by shopgoodwill-sniper** [comment]
FYI, We just released a new version of the ShopGoodwill Auction Sniper where we have completely rewritten the sniping engine inside it and the database in it as well to be more efficient and 100% accurate because the old version had some users complaining that sometimes it would miss auctions for them and our goal here is to make the sniping software 100% solid as possible so that it never fails and that is exactly what we have done here in this new version, we have made the sniping accuracy in it 100% accurate and never misses now, so please feel free to update to the latest version simply by running the install/update command from our homepage at Snipeable.com again, the new version numbers are as follows if you want to confirm you are indeed using the latest version once updated:

ShopGoodWill Auction Sniper Windows version is 25.03.23.1514
ShopGoodWill Auction Sniper Mac version is 25.03.23.1645

**Comment by shopgoodwill-sniper** [comment]
We're excited to announce a major update to Bid Sniper, featuring our new hosted sniping service and key improvements to standalone mode.

For a more reliable, hands-free experience, use the Hosted Mode option in the app. With hosted mode, your bids are executed from our servers—no need to keep your computer on.

To upgrade, visit Snipeable.com and run the install/update command again!

New Latest Versions:

Windows: 25.04.30.1737
Mac: 25.04.30.1730

Check your version by clicking "About" in the top-left menu of the Bid Sniper window.

Need help? We're here for you, let us know.

– The Snipeable.com Team
