### ISSUE TITLE
Payment options missing

### ISSUE THREAD

**Issue by thryme** [shopgoodwill-sniper/shopgoodwill-auction-sniper#60]
Today I went to purchase more snipes and the only option available is the monthly payment. Where did the payment options for 5/10 snipes go? I will not do the monthly option as I am not always at home bidding on things and it makes no sense for me.

**Comment by shopgoodwill-sniper** [comment]
Hi Thryme,

We have put back the pay-per-snipe and other options so you can check now and it will be there!

Best regards,
Customer Service
Snipeable.com

**Comment by shopgoodwill-sniper** [comment]
FYI, We just released a new version of the ShopGoodwill Auction Sniper where we have completely rewritten the sniping engine inside it and the database in it as well to be more efficient and 100% accurate because the old version had some users complaining that sometimes it would miss auctions for them and our goal here is to make the sniping software 100% solid as possible so that it never fails and that is exactly what we have done here in this new version, we have made the sniping accuracy in it 100% accurate and never misses now, so please feel free to update to the latest version simply by running the install/update command from our homepage at Snipeable.com again, the new version numbers are as follows if you want to confirm you are indeed using the latest version once updated:

ShopGoodWill Auction Sniper Windows version is 25.03.23.1514
ShopGoodWill Auction Sniper Mac version is 25.03.23.1645
